version: '3.6'

services:
    mongodev:
        image: 'mongo:latest'
        container_name: mongodev
        ports:
            - '27018:27017'

    rabbitmq:
        image: masstransit/rabbitmq
        container_name: 'rabbitmq'
        ports: [
            15672:15672,
            5672:5672       
        ]